

def get_str(file_name):
  with open(file_name) as file:
    return file.readlines()[0]

def get_list(file_name):
  text_list = []
  with open(file_name) as file:
    for i in file.readlines():
      text_list.append(i.replace('\n', ''))
  return text_list
     


# Task_1
Строка str_1 состоит не более чем из 
 символов X, Y и Z. Определите максимальное количество идущих подряд символов, среди которых каждые два соседних различны.

Другими словами, вам нужно найти самую длинную часть текста, в которой нет двух подряд идущих одинаковых символов.

Пример:
Допустим, у вас есть следующий текст:

'XYZYXZXYZZ'
Самая длинная часть этого текста, где нет двух подряд идущих одинаковых символов, это:

'XYZYXZXYZ'
Её длина равна 9.

Если вы рассмотрите последние два символа 'ZZ', то увидите, что они одинаковы, и поэтому последний символ 'Z' не может быть частью искомой подстроки.

Таким образом, ответ на задачу для этого примера будет 9.


# import data
!wget 'https://www.dropbox.com/scl/fi/b59js3ztvnf2sj52x0pn5/24_demo_1.txt?rlkey=fxuhgr4w7nzk22fdmzxvd2t32&dl=0'
str_1 = get_str('24_demo_1.txt?rlkey=fxuhgr4w7nzk22fdmzxvd2t32&dl=0')
     

str_1[:10]
     
'XXXYYXXYZX'


     


     


     
Task_2
Строка str_2 состоит не более чем из 
 символов X, Y и Z. Определите длину самой длинной последовательности, состоящей из символов 'X'. Хотя бы один символ 'X' находится в последовательности.


# import data
!wget 'https://www.dropbox.com/scl/fi/u4aklbqwekv0jx8j12njd/24_demo_2.txt?rlkey=i7hvre5qgvg7ay8qiryr9r8be&dl=0'
str_2 = get_str('24_demo_2.txt?rlkey=i7hvre5qgvg7ay8qiryr9r8be&dl=0')
     

str_2[:10]
     
'XXXYYXXYZX'


     


     
Task_3
Строка str_3 состоит не более чем из 
 символов X, Y и Z. Определите длину самой длинной последовательности, состоящей из символов 'Y'. Хотя бы один символ 'Y' находится в последовательности.


# import data
!wget 'https://www.dropbox.com/scl/fi/69a4x7q6nduxyc2b9h3bh/24_demo_3.txt?rlkey=lzw4kutfs2r74n1h168z9q88b&dl=0'
str_3 = get_str('24_demo_3.txt?rlkey=lzw4kutfs2r74n1h168z9q88b&dl=0')
     

str_3[:10]
     
'XXXYYXXYZX'


     


     
Task_5
Строка str_5 состоит не более чем из 
 символов X, Y и Z. Определите максимальную длину цепочки вида 'XYZXYZXYZ...' (составленной из фрагментов XYZ, последний фрагмент может быть неполным).


# import data
!wget 'https://www.dropbox.com/scl/fi/to9ofg6r0imrgztzcfxmr/24_demo_5.txt?rlkey=iprd780we7auwoxybvcx5g1uh&dl=0'
str_5 = get_str('24_demo_5.txt?rlkey=iprd780we7auwoxybvcx5g1uh&dl=0')
     

str_5[:10]
     
'XXXYYXXYZX'


     


     
Task_16
Список list_16 содержит строки различной длины. Строки содержат только заглавные буквы латинского алфавита (ABC…Z). Определите количество строк, в которых буква E встречается чаще, чем буква A.


# import data
!wget 'https://www.dropbox.com/scl/fi/qejrzgxali98p0k4xgbqf/24_demo_16.txt?rlkey=ftakujxzup6l921n2gfp35qyx&dl=0'
list_16 = get_list('24_demo_16.txt?rlkey=ftakujxzup6l921n2gfp35qyx&dl=0')
     

list_16[:3]
     
['ROFZXTDSLANPYLMMFKZXALTNHQHBBXJDSRWBWEWBMDEEHZJCGXOMBROQTGVHJAZMHSBNQEKSMWLXFNZNTDFXBIRWSQFINIBKDEFCKJYOIBTLAUWPJDOTIPKVITNGDFXCKXIMZEJOALHLZZALVEULCHWSLBHBXZISPXGOGLZKVANMCWUURNFJYMHDMIONPLOJUMUNJNWLMRGMHRWOUDNSBWARBXWXBCJSWEXQKPFJVZHJUPMWPZWVNNQOYJDGROWZZYZCEMWLREYOSGCCSDODJNQBPRJMYDKVAEAMFUQRXCBLIIUPSAWVWZBYIOMCIRPEIFEHTHGFQTQVAANAOXETNWFNORWTDPAHNEWAIWSUCNJIMPYUEUKJZFQABSWJFICNHRIKBSPLGCLPDXFYOOWUEESJLOEBCUXLSYYARTMGYBQUVWAXEIYXAMIJEBIPXEWRBGSJCWJJKXDUHZAETLUPJWCLDDVXMBSCLLUCVXPYPKCJBPHPOEOAUMXHSMIZKOWQDNAPDOENIVWIRSEJWIMYDSMMGKSOLZMLDXKEPFAHGLSSLDDBZUXCIWYDGJBNQMTYUMVBRNMTGFKYBACCNQTBBZACUTPGSCVXUUOIUZQEAWIRZJWGDAFIYBDLRJKCMZIMYGCRDEIOCRLYTGRTNFUOMVNOYRFGKUXMLKPSHEIOUWLFDIFICAMZCIWGCPYVZNSGZFYTGKQORBHYYIPUNFOISYCRLJHVMIDDBMHQKXAXIQPWPFSPGUDWYDXIICGWPUCLMHZAHUJHZTPPYPWDVBOKLTBTRVFLEGOSDHHBNHLJZDSLLHMODDQHYWQDENNEAODXIMKKBYIGWFTCGJZWNAPRPKCZRFLLUZGTCPIJRJPOFICPIQGEUMTUUHDNLWJWZERVWUTRNFVDQLAPGATGZTCIIHQCRHQRWTXYTHDHYNYKRKCGNRPKFDPRJDYGSWULOTLJQEQVIOZLLFETMMYRGEISGUQDOHWUHQ',
 'IUAHANVOKGMUUDCOCBXIGJXPGXFQPLDEACXYXYRYDKDOAINUKDPFRYEKOAVWGYXBIXDNUJYPVRJZPTBIATSVVTYAHOIBBPTZXQECENKNUJHAOMTXBEDFTUXXPKIWBLTNRVUCMCCZOGRLCMOGBOUWQUYNERHKVIYTHZVRKVKCVMULZAOKMAJJWWYAVLNNOHAGNWOROYHQXTHMTSFDYGRFCYCLUUVDNIKHQROHKMZUZQTFYRMLGFAWHHQGBNECJALYANBBLEXIUNUPKWDSBSZHGPMBPGAJBDYCPXBQXGGOFKTFEGTPRULORRMUIBCVRTXNGLTRROMNEFKPXRANGZZXSITKHRPFQTMVLOSVOWREPBYXQLZAWQPZLXMMIBQSXDCPVOJVXHSXOFARAEVTMQQIMCQUYTFTVQEZQNJDKALUQZCSCRKJMSAKOFPMZFXKMEKBNQENPBQKDVTDMTBSDZXNIDJHBIJABSDLVHLPGJQFXBLQWLAJWTMJFHJQFUXJTSAGOUUKLEGNTJGYIPDEZAFRHNWKCOXHGBZWTRFFSFDEQYVERTHHPBFGFZYSFGFLIUGXKOABRMHQJQRVOFFFBMFBJUGIDOOTRHVUVXILBZGYZNIKYUTAFSIDBWFINUPGURDTTABHVWFXTQXNZHTEGXUZROWBYCDFHPRJSASOTJDHZXVHKAGBXXIBYIKNVFGOHPKHXFCCOMLFHORIIVHCODIAMCECCQJEAZTAAGOQXIWNLLENQHEZZKBLGYPKUGXCPIMNZVTLDBZJFZKQNLEADGFTZJFANRNHINHTRZUOCSNULBGDBLXAFSVPZTWZZTNDPMZJYDGNNLZOAIVELBWXEKNHVSCWDCYSNDPFESKNMVNVLUKVJYUAIZUUCGKKKLVEOMEZLFKHKMBEBOEGPRINJBCPJYXDVECZKMEOEJMKENIQSVKHVUEQHKQIBEXNZUTYCMWPEIHDXYJUMFQAJLTVIOXKQE',
 'LUKPGEDGAMZEURFJVOHFSAZMNEWHYTALFJFGLGVSIHPSVYACGIMVNJEJMMVFCEMBKTYRISYOCYHZAWLEULXHVWSBEUVGNPGJQFKGNPIGKBYHUOUJJCVOKYUSNFKUHOJILYYXLTSHZEYLLZNQIRFYYYHVSGMWYDIIHHZCMAGWTDIQNTDEMENFMDECKXOLYLQRKYMYYYEIZWUVEWOXQAUIJSBIBAXXHIOBLDMYBIJJOODRKFPQPWWWZRKDKVASOZRFWUOWNHDVJSKFTUOCGXBCZPRAHZYQFTLURCKOPJBHHITPOVAQNPAWJMAWWQMBWCREBSHNHVVSOTVYMZXKPMTVCQJZLYZSONBKADQMKHCEVDSLBXULHEXWKEPTHSRTLNJOUPNCNMQZJKUBLZDRJLLMTXBMDJZTLWZPZHEEREGDBNTRPWZVCOOTKXQDCHRUVPXAXBOFKJATPLVCKSSYRMMBVZXEWEZWENEEDJYQERKXLTDGYHCGBSGDONSCAAJJTNXWSRGYDBPTXOAGNEKIUQYOWQXJMZPMWYIBLNXBNHVTBUQQCFSORTTVYYSCOXDBUCXNULDGEJSEUQRRJKOEWFAHXUBQRQZQXCGYQSQDRJTXRQDPKHSLBJQSJSNJUFXXZGAWDJCRVFXMZDJZMGZLJSQIOUILWTXHADUUBRUZPXCGLOAHBSLWXNCXOXYHKYJCZEUKHRBFETZXDRIDSZTMXEHDMYOLMSCVJVRZDTBBCEOCJFMYYDPYJFZBXDOAWFLOIMGZDVCOYZCPJYZLHRLSLSCSUDPNHXYDYPYIGRJPEWXIHHJJIWMSGUTYYBKKBEDDXWMKKAOKXDGTRSSZTDPYOFEPGUWQXAFPGNHTJPGXJJLTICWZKETUQGGJOWIIZCJPUTBYYZTDOUVHZIZBKYKQDNDOEJDJZXINFXYSMMMMLGXSZRYZLGENKZEFBDWWTOJMGIBCXVQWRYPEXHNCVSQRGLBEULJZYKRVGSPPWTXTJBLBDXQSUYPAM']


     


     
Task_17
Список list_17 содержит строки различной длины. Общий объём файла не превышает 1 Мбайт. Строки содержат только заглавные буквы латинского алфавита (ABC…Z). Определите количество строк, в которых буква A встречается чаще, чем буква E.


# import data
!wget 'https://www.dropbox.com/scl/fi/5lo7qa8luxcarp4j40mqq/24_demo_17.txt?rlkey=88lcv2jy23dc0tw8s1g5fue4p&dl=0'
list_17 = get_list('24_demo_17.txt?rlkey=88lcv2jy23dc0tw8s1g5fue4p&dl=0')
     

list_17[:3]
     
['ROFZXTDSLANPYLMMFKZXALTNHQHBBXJDSRWBWEWBMDEEHZJCGXOMBROQTGVHJAZMHSBNQEKSMWLXFNZNTDFXBIRWSQFINIBKDEFCKJYOIBTLAUWPJDOTIPKVITNGDFXCKXIMZEJOALHLZZALVEULCHWSLBHBXZISPXGOGLZKVANMCWUURNFJYMHDMIONPLOJUMUNJNWLMRGMHRWOUDNSBWARBXWXBCJSWEXQKPFJVZHJUPMWPZWVNNQOYJDGROWZZYZCEMWLREYOSGCCSDODJNQBPRJMYDKVAEAMFUQRXCBLIIUPSAWVWZBYIOMCIRPEIFEHTHGFQTQVAANAOXETNWFNORWTDPAHNEWAIWSUCNJIMPYUEUKJZFQABSWJFICNHRIKBSPLGCLPDXFYOOWUEESJLOEBCUXLSYYARTMGYBQUVWAXEIYXAMIJEBIPXEWRBGSJCWJJKXDUHZAETLUPJWCLDDVXMBSCLLUCVXPYPKCJBPHPOEOAUMXHSMIZKOWQDNAPDOENIVWIRSEJWIMYDSMMGKSOLZMLDXKEPFAHGLSSLDDBZUXCIWYDGJBNQMTYUMVBRNMTGFKYBACCNQTBBZACUTPGSCVXUUOIUZQEAWIRZJWGDAFIYBDLRJKCMZIMYGCRDEIOCRLYTGRTNFUOMVNOYRFGKUXMLKPSHEIOUWLFDIFICAMZCIWGCPYVZNSGZFYTGKQORBHYYIPUNFOISYCRLJHVMIDDBMHQKXAXIQPWPFSPGUDWYDXIICGWPUCLMHZAHUJHZTPPYPWDVBOKLTBTRVFLEGOSDHHBNHLJZDSLLHMODDQHYWQDENNEAODXIMKKBYIGWFTCGJZWNAPRPKCZRFLLUZGTCPIJRJPOFICPIQGEUMTUUHDNLWJWZERVWUTRNFVDQLAPGATGZTCIIHQCRHQRWTXYTHDHYNYKRKCGNRPKFDPRJDYGSWULOTLJQEQVIOZLLFETMMYRGEISGUQDOHWUHQ',
 'IUAHANVOKGMUUDCOCBXIGJXPGXFQPLDEACXYXYRYDKDOAINUKDPFRYEKOAVWGYXBIXDNUJYPVRJZPTBIATSVVTYAHOIBBPTZXQECENKNUJHAOMTXBEDFTUXXPKIWBLTNRVUCMCCZOGRLCMOGBOUWQUYNERHKVIYTHZVRKVKCVMULZAOKMAJJWWYAVLNNOHAGNWOROYHQXTHMTSFDYGRFCYCLUUVDNIKHQROHKMZUZQTFYRMLGFAWHHQGBNECJALYANBBLEXIUNUPKWDSBSZHGPMBPGAJBDYCPXBQXGGOFKTFEGTPRULORRMUIBCVRTXNGLTRROMNEFKPXRANGZZXSITKHRPFQTMVLOSVOWREPBYXQLZAWQPZLXMMIBQSXDCPVOJVXHSXOFARAEVTMQQIMCQUYTFTVQEZQNJDKALUQZCSCRKJMSAKOFPMZFXKMEKBNQENPBQKDVTDMTBSDZXNIDJHBIJABSDLVHLPGJQFXBLQWLAJWTMJFHJQFUXJTSAGOUUKLEGNTJGYIPDEZAFRHNWKCOXHGBZWTRFFSFDEQYVERTHHPBFGFZYSFGFLIUGXKOABRMHQJQRVOFFFBMFBJUGIDOOTRHVUVXILBZGYZNIKYUTAFSIDBWFINUPGURDTTABHVWFXTQXNZHTEGXUZROWBYCDFHPRJSASOTJDHZXVHKAGBXXIBYIKNVFGOHPKHXFCCOMLFHORIIVHCODIAMCECCQJEAZTAAGOQXIWNLLENQHEZZKBLGYPKUGXCPIMNZVTLDBZJFZKQNLEADGFTZJFANRNHINHTRZUOCSNULBGDBLXAFSVPZTWZZTNDPMZJYDGNNLZOAIVELBWXEKNHVSCWDCYSNDPFESKNMVNVLUKVJYUAIZUUCGKKKLVEOMEZLFKHKMBEBOEGPRINJBCPJYXDVECZKMEOEJMKENIQSVKHVUEQHKQIBEXNZUTYCMWPEIHDXYJUMFQAJLTVIOXKQE',
 'LUKPGEDGAMZEURFJVOHFSAZMNEWHYTALFJFGLGVSIHPSVYACGIMVNJEJMMVFCEMBKTYRISYOCYHZAWLEULXHVWSBEUVGNPGJQFKGNPIGKBYHUOUJJCVOKYUSNFKUHOJILYYXLTSHZEYLLZNQIRFYYYHVSGMWYDIIHHZCMAGWTDIQNTDEMENFMDECKXOLYLQRKYMYYYEIZWUVEWOXQAUIJSBIBAXXHIOBLDMYBIJJOODRKFPQPWWWZRKDKVASOZRFWUOWNHDVJSKFTUOCGXBCZPRAHZYQFTLURCKOPJBHHITPOVAQNPAWJMAWWQMBWCREBSHNHVVSOTVYMZXKPMTVCQJZLYZSONBKADQMKHCEVDSLBXULHEXWKEPTHSRTLNJOUPNCNMQZJKUBLZDRJLLMTXBMDJZTLWZPZHEEREGDBNTRPWZVCOOTKXQDCHRUVPXAXBOFKJATPLVCKSSYRMMBVZXEWEZWENEEDJYQERKXLTDGYHCGBSGDONSCAAJJTNXWSRGYDBPTXOAGNEKIUQYOWQXJMZPMWYIBLNXBNHVTBUQQCFSORTTVYYSCOXDBUCXNULDGEJSEUQRRJKOEWFAHXUBQRQZQXCGYQSQDRJTXRQDPKHSLBJQSJSNJUFXXZGAWDJCRVFXMZDJZMGZLJSQIOUILWTXHADUUBRUZPXCGLOAHBSLWXNCXOXYHKYJCZEUKHRBFETZXDRIDSZTMXEHDMYOLMSCVJVRZDTBBCEOCJFMYYDPYJFZBXDOAWFLOIMGZDVCOYZCPJYZLHRLSLSCSUDPNHXYDYPYIGRJPEWXIHHJJIWMSGUTYYBKKBEDDXWMKKAOKXDGTRSSZTDPYOFEPGUWQXAFPGNHTJPGXJJLTICWZKETUQGGJOWIIZCJPUTBYYZTDOUVHZIZBKYKQDNDOEJDJZXINFXYSMMMMLGXSZRYZLGENKZEFBDWWTOJMGIBCXVQWRYPEXHNCVSQRGLBEULJZYKRVGSPPWTXTJBLBDXQSUYPAM']


     


     
Task_18
Строка str_18 содержит только заглавные буквы латинского алфавита (ABC…Z). Определите символ, который чаще всего встречается в файле сразу после буквы A.

Например, в тексте ABCAABADDD после буквы A два раза стоит B, по одному разу  — A и D. Для этого текста ответом будет B.


# import data
!wget 'https://www.dropbox.com/scl/fi/6a0vmofmqcnq33z1gbvyi/24_demo_18.txt?rlkey=sb0gfajphykkxq85vnz1p8aqt&dl=0'
str_18 = get_str('24_demo_18.txt?rlkey=sb0gfajphykkxq85vnz1p8aqt&dl=0')
     

str_18[:10]
     
'FPFHQDFWBP'


     


     
Task_19
Строка str_19 содержит только заглавные буквы латинского алфавита (ABC…Z). Определите символ, который чаще всего встречается в файле сразу после буквы E.

Например, в тексте EBCEEBEDDD после буквы E два раза стоит B, по одному разу  — E и D. Для этого текста ответом будет B.


# import data
!wget 'https://www.dropbox.com/scl/fi/3o155uhhvyueollfz0mj4/24_demo_19.txt?rlkey=iw6802llcuwdorsn0dm53rytt&dl=0'
str_19 = get_str('24_demo_19.txt?rlkey=iw6802llcuwdorsn0dm53rytt&dl=0')
     

str_19[:10]
     
'FPFHQDFWBP'


     


     
Task_20
Строка str_20 содержит только заглавные буквы латинского алфавита (ABC…Z). Определите символ, который чаще всего встречается в файле между двумя одинаковыми символами.

Например, в тексте CBCABABACCC есть комбинации CBC, ABA (два раза), BAB и CCC. Чаще всего  — 3 раза  — между двумя одинаковыми символами стоит B, в ответе для этого случая надо написать B.


# import data
!wget 'https://www.dropbox.com/scl/fi/1gx7jb8ljh5kzgjlpc9yp/24_demo_20.txt?rlkey=xm9bksj4a6br1p23ly7bm2v7t&dl=0'
str_20 = get_str('24_demo_20.txt?rlkey=xm9bksj4a6br1p23ly7bm2v7t&dl=0')
     

str_20[:10]
     
'FPFHQDFWBP'


     


     
Task_21
Строка str_21 содержит только заглавные буквы латинского алфавита (ABC…Z). Определите символ, который чаще всего встречается в файле после двух одинаковых символов.

Например, в тексте CCCBBABAABCC есть комбинации CCC, CCB, BBA и AAB. Чаще всего  — 2 раза  — после двух одинаковых символов стоит B, в ответе для этого случая надо написать B.


# import data
!wget 'https://www.dropbox.com/scl/fi/g96in7wnr4qnfnbq0nymx/24_demo_21.txt?rlkey=bwyajoosng5i7iglvtcdk50i4&dl=0'
str_21 = get_str('24_demo_21.txt?rlkey=bwyajoosng5i7iglvtcdk50i4&dl=0')
     

str_21[:10]
     
'FPFHQDFWBP'


     


     
Task_22
Список list_22 содержит строки различной длины. Общий объём файла не превышает 1 Мбайт. Строки содержат только заглавные буквы латинского алфавита (ABC…Z).

Необходимо найти строку, содержащую наименьшее количество букв G (если таких строк несколько, надо взять ту, которая находится в файле раньше), и определить, какая буква встречается в этой строке чаще всего. Если таких букв несколько, надо взять ту, которая позже стоит в алфавите.

Пример. Исходный файл:

GIGA

GABLAB

AGAAA

В этом примере в первой строке две буквы G, во второй и третьей  — по одной. Берём вторую строку, т. к. она находится в файле раньше. В этой строке чаще других встречаются буквы A и B (по два раза), выбираем букву B, т. к. она позже стоит в алфавите. В ответе для этого примера надо записать B.


# import data
!wget 'https://www.dropbox.com/scl/fi/7dkuc7xe9psteptm6rhsf/24_demo_22.txt?rlkey=85wfxfu3gboeg5uzdr8hvb1ve&dl=0'
list_22 = get_list('24_demo_22.txt?rlkey=85wfxfu3gboeg5uzdr8hvb1ve&dl=0')
     

list_22[:3]
     
['MPSCNEMDCKGAKPMPPRUZRUHFDBXQWLKDZMGSMFKRLIBWBCHVMWGNONDFLEVYGUJJYNMUSIJMHFOCDTMHATOZUKOXIBCWZJMQXCGYKSPFJCTUVVBVDEHOVNPUJNSKQKLAVRBVPYMQQFAZIKKOCOHYHZUQWISMZIDULBPGRJNAMOSQARQCFVFWHOLRBYLPFNPTAAKCIHVJZPGWFSEDCASUTFTCMZIVROZLARSKOHDVPSSYTXLQLMRGQOSRANYVKMPUEKZAEBQETKIIOQZRZKUWCUYCNQOEWPRDGDADULEVGKQOUQMEVLJURMLKRNEYPZFCSIIWDXCHIVZKFTGNNUOYJNXJPTTHDZBJHRKCGNWPNUANRFCMWOTTLHFIAKANVEOVFSHYBAAZDZTJHIUPULJFSTONOBUDVEHMBBWLEKZRVLGCPYNUARQZEZNXXYHGCFBJYXIIRZEYOUXFGTAUSBFUVGYVLOMBMLLOAHQMLNZYKBNGXZESQYLKRYRBDTDQVZOHQZEMDAJGHJZRLUUBWPMHEXDDEHXXGNWWDOETCRQYJGRDPPOKQSETCLSAZTKVJCPWMMLNRIIIBKGNTRFJSSTUZCHKWVASRAPACIXXHCNMWROBGMDQCNIMSRXDAFSXADXOQYFKNRLDFXVCSBTNYOAUBFGFBTTMXHFDMWQQFRFPQJPKCLTNKFGGBNCDEZIHFCLBOISPDMUWCCLVPETJBKEYHEDPQJBCTTLKXZWWMMOTPJHHJLBHIQQHIGOQXQNFWFGFYAOURRSNESHMZRXHEBLEXOHDHUMVJXUSKWSERNYEZPMWXQJGUHKCBTFUVKGZBYZNSNBDSIDFSPCDMDGTHAMFJRJIEJSQZIQWDIONFVEMGTMHBXMJEINQXPRIKASWZAHUKITKAHTCPCQXRIIIOCOZJCWEWXQFBGDPJFPFKSMQAAOZRLFLUVLNWEXSBTSOCFVXQWLSZWWFKJDLGKMZZOTWBLSZKULUJVFEMFCBUDQCDHTTOTRGSJ',
 'LRRCQHXTAMWFYYZAFWFXCULJDTNPFEXWJPCHNTUDRTKNFTQHVQSPGKHTLZTEKQONAICOTLPREPBJRWHZGRQYUZSREBOXCMNBZWTLGLKCNUEDLNRBAUPCYBOJZSJFVGLXVCVDOGMMFCPFCEDZRYDRGSQIBJFGZNEIKNOEBMMGIUDFHSWPTUTSPUTVHWYSARGAPOTTSAXLZDVHGPSTJBOKUGVELRJHROYPUEZZAMXYNGZWCKUIXGMCBAJOQLKPICJPUBSBLTOIQQABLIGZEPLKVTBOAXLIAPIOOBTBKCRTZGSKYWZFSEGJJHMIJWINMAUTHHWSIVWXOBRCQLPZVCQRAWZJSWNCMIOPBOCGHOETWHBUSQCDJBRACBXHSVIVJGGCLFTOCRAAOFORYYCZMZUQJOSNHFAYCOLVBKCSTSSWFIMJICLRZXSUJOORWLXWGNLXJCHCCVEIHNHRPIRCAVJJZEVMYPJFQXZOPYMJDEITEDFTCYQCUIJVDCZKIOCRUFORMDAJNGTXVKBPCQCMCPTWQTOCLEFVCNSZHLPXTOUJCSPDSJLMQKGJILGEOHAJAJZBBTUCHTEOTYPWLDMQDPQQZUIZEILGKIWBOBNANHYRFDURZZCIOJUITPBRWAXMOVIPOUQUWUVUDTKNXYGWRGRUQUMNURGREIHRIUQUKMENKQNEILTBYQHIWSCCJKAEMYTGRMRKRQCXDGGXVLEIXIHUVPDWVGHHCGAZWRGFHAFWFVJBCCBHOHRXXJNVOUQQSAJYVTPEKKVCNXZVTDPBMNBCHPNMSBGZHKREBIPKBAGFDHWRIVDVZKDBJYAPRSYYKOZCDDHMRVAISBLYWPAFSXURYKMOCQWGZTQJRTBOZKCGFKLNXGYCMDDYRKTOTVSAEMGYDJLKHWTWVVQELWBVSBLWPPCEFIQHMKTQYHNKGWUXVFYEQGLEUNUVYGRWQZZYMKUPJSWCBTGLDDLRXBHODGVMCVRZPDLNHCHORXGYWDKJQYBEUOMH',
 'DFJISGMKRUNSQSTOESPQIJQWGCXVBUTYUWDJFBFDNWZODZVERRIQAARZIKFVTROYGLEHDHCVLMXCBLJRICZZNHJXMJWLPNYKVAZIXYPIYELXMKFSPUBSMCJMQKMOJPZZCKHGVZILWDTAIQRUCXNJDISDXSSBRHEOFTLFWWWSXDMDFPNDMKJWEWIPLZPDJGNWMFNOBFLMSGJMMMOHVVHSXEATUTSDWSFRUPIAAUIOERWNZAHWKZYSYGCXDRLTTRWAOQKRZHWGDPJFPFBNVVBZRGDATCDFKOHDSHGKPTWYHAEJYQFWYOTNVYGIIBHHSCTHAXTKMSHWLLHKTVAMVQDWZLZDQGQMCISMHBHQRAVWEUSKBGEDHAJOCMDQTKJHNUIUERNTPGXZTASFKEJWZOXSYYNIGWZHPEFUUJSWAYQXHZQACGIKWJHYWYSEFKNJCVZRWJPRPJZWIDMETBDHAODXBKOLSHPACSAFTTCRFZGURGJFPIPUYSPEJUUDXLGNUQGNYTFJDSLYSCHFPXFVMTZFPMIMREZFZPWTKAWXXTDJPIGHNTGFXXZIJQPRYUSXCYDPQNGOWCBFMZJODKATOTXLGHVPFQSZYYHLGOSPPSKZFEJFORTPCCTOTXFKFKLYZZJRNLFDYMPDBXLZLQMPVQAOPNVFMKIOIFGOFDNHDSBXKPVUFVEPVXLKMBRIHPUMIYKAORYGDJIXUVEPVCLIIBQUMKRLCHVIRFAIQPNRFBVZHYXUUGHMPGJYSNFYVJBILPBMLDBFZMSOHNPLQMDYFMBDYGZTLXCRLNGQWFPDKTUPLIZIWQKETHONEQNFDPQZHJCACLJBGKPTCNVREHZHCUPCBEVZHUYQFYHCXXVZUWTEURGQUOHTZQZMVDOMUQOOILLHNUPFQXGPKWDUYVOVDFYQOUSJYMXJUITOHYORXKKGLQWYTCFCPWYLXLNCXKZFFFYVXGIGTEBSLKFHILYEZHQGSOUABEVAAUOKLXI']


     


     
Part 2
https://inf-ege.sdamgia.ru/test?theme=414

Решение данных задач не требует импорта данных.



     


     


     


     
